name: Test

on:
  push:
    branches-ignore: [ master ]
  pull_request:
    branches: [ master ]
env:
  GITHUB_TOKEN: ${{ github.token }}
  LINT_VERSION: "1.25.1"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: next version
      run: |
            npm install @semantic-release/exec -D
            npx semantic-release --dry-run

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v$LINT_VERSION

    - name: go-linter
      run: |
          $(go env GOPATH)/bin/golangci-lint run -v

    - name: test
      run: |
        FILE=./VERSION.env
        npm install @semantic-release/exec -D
        npx semantic-release --dry-run
        if [ -f "$FILE" ]; then
            cat VERSION.env
            source VERSION.env
        fi
        go test -coverprofile=go.txt -v ./...
        go run main.go
        go run main.go version
        go run main.go events
        go run main.go events -f volcanoes,wildfires
        go run main.go events -f volcanoes,wildfires -o table
        go run main.go events -f volcanoes,wildfires -o json
        go run main.go events -o table
        go run main.go events -d
        go run main.go events -o json
    - name: build & execute
      run: |
        echo "--------------------------------------------------"
        go build -ldflags="-X 'github.com/karl-cardenas-coding/disaster-cli/cmd.VersionString=$VERSION'" -o=disaster -v
        ./disaster events -d
        ./disaster events -o table
        ./disaster events -o json
        ./disaster version
        ./disaster events -f volcanoes,wildfires
        ./disaster events -f volcanoes,wildfires -o table
        ./disaster events -f volcanoes,wildfires -o json
    - name: build & verfy update feature
      run: |
        go build -ldflags="-X 'github.com/karl-cardenas-coding/disaster-cli/cmd.VersionString=1.0.0'" -o=disaster -v
        ./disaster version
        mkdir tempbin
        echo 'Y' | ./disaster update -l ./tempbin/
        sleep 5
        chmod 775 disaster
        ./disaster version
    - uses: actions/upload-artifact@v1
      with:
        name: test-results
        path: go.txt
